### ISSUE TITLE
自分宛てのメンションとリツイートについては、識別しやすくしてほしい

### ISSUE THREAD

**Issue by jiro-aqua** [moko256/twitlatte#10]
要検討

**Comment by moko256** [comment]
太さと下線を加えてみました

![screenshot_20190224-160034_1](https://user-images.githubusercontent.com/16546008/53296265-06d98000-384f-11e9-9fed-8982c268f4ef.jpg)
![screenshot_20190224-160940_1](https://user-images.githubusercontent.com/16546008/53296267-0ccf6100-384f-11e9-8ba4-fdee00b070b9.jpg)
