### ISSUE TITLE
bug found in twitlatte app ( add other account button is not working correctly  )

### ISSUE THREAD

**Issue by nasirshah1813** [moko256/twitlatte#19]
#### Project Information

* Repository:  https://github.com/moko256/twitlatte

* Project Name:  twitlatte

* Publisher   : moko256.lab

#### Expected behavior
according to my knowledge when i click on the other account button the application should open the new tab  where i write the my account details 

#### Actual behavior
after open the application when i open the application and click on the account button the account button is not working properly you can see in bug video 

#### How to reproduce
* [download ](https://f-droid.org/packages/com.github.moko256.twitlatte/)and open the application
* click on setting button
* click on account button
* note the bug 
* Browser: twitlatte app Version 1.1.1 
* Operating system: android version 6.0.1
 

#### Recording Of The Bug
https://youtu.be/yjdByxVIDZw

#### Proof of Work Done   
https://github.com/nasirshah1813

**Comment by moko256** [comment]
It's my translation problem. I made this button as it means "Login with other account".
I'll fix. Thank you.

**Comment by IzzySoft** [comment]
@nasirshah1813 to add an(other) account, use the navigation pane:

[![pane](https://lh3.googleusercontent.com/QpWGWQ92XsAHA6W77sGV-3Xn8uXwaNzTylC_UmBd3okFAfnDm7MDzApmnJGfj6XoUg=w200)](https://raw.githubusercontent.com/moko256/twitlatte/master/readme_image/navbar.png)

**Comment by danvilar** [comment]
the real problem is if you try to add another account from the same service (for example, twitter) it will automatically relogin in the account in cache you logged in first.

**Comment by moko256** [comment]
@danvilar I understood it.
TwitLatte uses `oauth/authenticate` and Twitter automatically returns tokens of the accounts we are loggining in.
As a result,we cannot logout and sign in other account with Twitter when we start authorization.
I'll fix it soon. Thank you.

**Comment by danvilar** [comment]
Glad to be helpful
