### ISSUE TITLE
App crashes on screen rotation

### ISSUE THREAD

**Issue by neupanedipen** [moko256/twitlatte#20]
#### Expected behavior<br>
The app is supposed to be stable during screen rotation.<br>
#### Actual behavior<br>
But the app crashes when I change the screen orientation before granting permissions for location services on create post page.<br>
#### How to reproduce<br>
1. Install the app.<br>
2. Launch the app.<br>
3. Authorise your twitter to open with this app.<br>
4. Click on + icon from bottom right corner of the app.<br>
5. Now click on the check box which says &quot;Add location&quot; and change the screen orientation to landscape before granting the permissions.<br>
The app crashes.<br>
* App Version: 1.1.0<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/oIW03gWYLd8

**Comment by moko256** [comment]
Thank you!
This issue was fixed by commit [aa6089](https://github.com/moko256/twitlatte/commit/aa60895f71982c70f5f4b7a35f28c3f25bb42e9f)
