### ISSUE TITLE
A minor bug on login page

### ISSUE THREAD

**Issue by MrLaaky** [moko256/twitlatte#26]
Twitlatte 1.2.2 from Google Play.
Hello,
it might not even be a bug and it is so on purpose, but here it is.
AFTER I am successfully logged in with my Twitter account I go to the sidebar where I see my account name, timeline, mentions... After that I click on my name and go to Login with another account. Two options appear, one for Twitter and one for Mastodon. Everything OK so far, I can go FORWARD with log in but I cannot go BACK to the feed, it simply exits from the app if I press back button on my phone, BUT if I repeat the process and login with the Twitter account(it's is done automatically after it goes first again to the external site)  and I get back to the Twitter feed. In short, after getting to the login page there is no way back unless I sign in again. Otherwise really great work with the app!
Keep it up :) Best wishes.

**Comment by moko256** [comment]
Ok, I see. I will fix it. Thank you!
