### ISSUE TITLE
Modify layout from quoted tweet

### ISSUE THREAD

**Issue by Tvax** [moko256/twitlatte#32]
It's not easy telling if the tweet is quoted or not, an easy solution would be to make the quoted tweet looking like Twidere or the official Twitter app. Which in my opinion is clearer than that we have on this app.

**Comment by moko256** [comment]
I added layout of picture of quoted tweet.

![image](https://user-images.githubusercontent.com/16546008/42631146-3f0d410c-8614-11e8-9d1e-74bac6aad9d0.png)
