### ISSUE TITLE
[Feature request] Select account when opening app from link

### ISSUE THREAD

**Issue by sirtao** [moko256/twitlatte#40]
Currently Twitlatte opens the app on the latest used account when opening from an external link.

This can be an issue when opening, say, a Mastodon link when I last used a Twitter account, as it wouldn't load. And viceversa, of course.

Having a pop-up letting the user chose with what account open the link would be optimal.
This might even implement issue #31 by having a "anonymous\not logged" choice as well.

**Comment by moko256** [comment]
Hello.
I implemented it and published v1.6.5!
