### ISSUE TITLE
Twitlatte app permanently suspended by Twitter (still usable for Mastodon)

### ISSUE THREAD

**Issue by Symbian9** [moko256/twitlatte#54]
- https://twitter.com/m3lang3/status/1124352463572697088

> Sigh. Twitlatte can no longer tweet or retweet. Hoping I won't have to resort to the mobile interface...

I also tested and can confirm that today I can't do any actions using Twitlatte.

**Comment by moko256** [comment]
Twitter is restricting twitlatte's api key.
I sent the request to cancell it.

**Comment by ckuethe** [comment]
![Screenshot_20190503-124329_twitlatte](https://user-images.githubusercontent.com/1131751/57187055-37b4e180-6e9e-11e9-93e4-963ca1808152.jpg)

Me too.

#49 makes me think ... could you add an advanced option for users to fill in their own API keys (I have a few for some of my private tools)

**Comment by moko256** [comment]
I got the reply from Twitter:

>Thanks for reaching out. Your app was restricted for sending a large
>volume of unsolicited and/or repeat @mentions. This is prohibited by
>the Twitter Rules:
>
>Spam: You may not use the Twitter service for the purpose of spamming
>anyone. What constitutes “spamming” will evolve as we respond to new
>tricks and tactics by spammers. Some of the factors that we take into
>account when determining what conduct is considered to be spamming are:
>
>if you send large numbers of unsolicited replies or mentions;
>if you send large numbers of duplicate replies or mentions;
>
>Note that this behavior is not allowed regardless of whether or not it
>is automated. Per the Automation Rules if you are sending automated
>@mentions the recipient or mentioned user(s) must have requested or
>have clearly indicated an intent on Twitter  to be contacted by you.
>
>As a next step please respond to this email listing the measures that
>you have taken to limit this behavior on your platform.
>
>Please let us know if you have any questions.
>
>Regards,
>
>Twitter Platform Operations

**Comment by Symbian9** [comment]
> Your app was restricted for sending a large
volume of unsolicited and/or repeat `@mentions`

According this rule, official Twitter clients should be restricted as well as Twitter website too. :-/

**Comment by moko256** [comment]
Restriction was lifted by Twitter. Have fun!

**Comment by moko256** [comment]
Note: Twitlatte will show some notice if user is sending too much @mentions instantly to follow Twitter's rule.

**Comment by Symbian9** [comment]
> twitlatte will show

`v1.8.1` coming?

**Comment by moko256** [comment]
Yes, in a few days.

**Comment by luciomarinelli** [comment]
> Restriction was lifted by Twitter. Have fun!

I am still having this issue; already tried to logout and login without results.
P.S. Twitlatte rocks!

**Comment by 7heo** [comment]
I too am having issues all the time with the twitlatte API key. 

> ![Screenshot_20190503-124329_twitlatte](https://user-images.githubusercontent.com/1131751/57187055-37b4e180-6e9e-11e9-93e4-963ca1808152.jpg)
> 
> Me too.
> 
> #49 makes me think ... could you add an advanced option for users to fill in their own API keys (I have a few for some of my private tools)

This is the only way to make twitlatte work reliably for all of us, as we can fairly expect twitter not to help and/or care, ever.

**Comment by sirtao** [comment]
Still happening :(

**Comment by moko256** [comment]
Again restricted :(
I've already sent request to Twitter, so please wait a few days.

**Comment by 7heo** [comment]
> Again restricted :(
> I've already sent request to Twitter, so please wait a few days.

How about providing us with a way to use our own API key, instead?

**Comment by Symbian9** [comment]
> > Again restricted :(
> >
> > I've already sent request to Twitter, so please wait a few days.
>
> How about providing us with a way to use our own API key, instead?

I temporary switched to [Twidere](https://f-droid.org/en/packages/org.mariotaku.twidere/) and, as I know, it has such function

- https://github.com/TwidereProject/Twidere-Android

**Comment by ckuethe** [comment]
They still haven't unrestricted it. Being able to use our own api keys would be great

**Comment by spaaaaam** [comment]
Hi, 

I'm having the same problem here.

Thx

**Comment by moko256** [comment]
v1.9.0 released

**Comment by madmuffinz** [comment]
Is using the key available? I am on 1.9.2

**Comment by moko256** [comment]
> Is using the key available? I am on 1.9.2
No, it's not. Twitter hasn't reply me yet.

**Comment by moko256** [comment]
Twitter lifted twitlatte's restriction.

**Comment by ckuethe** [comment]
It's broken again

**Comment by moko256** [comment]
Rate limit is too few to post (like, retweet, tweet), because it is shared in all users.
I'll send request to have it's limit increased.

**Comment by 7heo** [comment]
>> Is using the key available? I am on 1.9.2
> No, it's not. Twitter hasn't reply me yet.

@moko256 I think what @madmuffinz was asking is if we can already set a new API key in the version 1.9.2 of the software...

**Comment by moko256** [comment]
@7heo You can set your API key in v1.9.2 when you authorize.

**Comment by demolg** [comment]
@moko256 it seems that the API key was limitted once again.

**Comment by moko256** [comment]
@demolg I sent the request to lift the restriction.

**Comment by moko256** [comment]
Twitter lifted the restriction.

**Comment by michaelprager** [comment]
It seems the API key is restricted again

**Comment by moko256** [comment]
This app was permanently suspended by Twitter.
I've requested to lift a read restriction, but it was no good...

* Please use ohter app.
* If you have a Twitter developer account, create a new app key and enter it in  login > ⁝ menu > "Use another consumer token", to keep using this app (Note: Do not publish your key. It is dangerous.)


Thank you for using twitlatte.

**Comment by IzzySoft** [comment]
Sad news. Guess I'll then "permanently suspend Twitter", and won't use it anymore. I've switched to Mastodon long ango anyway, and used Twitter read-only to follow some accounts not available in the Fediverse. Time to quit it seems.

Thanks for maintaining it so long despite the permanent trouble Twitter was causing your app, @moko256!

For those looking for other FOSS clients:

* [andStatus](https://f-droid.org/packages/org.andstatus.app/)
* [Twidere](https://f-droid.org/packages/org.mariotaku.twidere/) (looks like its author [said good-bye, too](https://github.com/TwidereProject/Twidere-Android))
* [ReoTwé](https://f-droid.org/packages/de.digisocken.reotwe/) (also no longer maintained – [Github repo archived](https://github.com/no-go/ReoTwe))
* [Shitter](https://apt.izzysoft.de/fdroid/index/apk/org.nuclearfog.twidda)

Afraid that's all – remaining FOSS clients are "long abandoned" (last update 2018 or before). If you don't care for trackers and Play Store, [see my list](https://android.izzysoft.de/applists/category/named/network_twitter) for more alternatives.

@moko256 shall we update the description for F-Droid then? It currently reads:

> SNS client specialized to read in chronorogical order. You can access Twitter, Mastodon and Pleroma with API. ''Twitlatte'' supports multiple accounts.

I'd suggest adding a note, pointing here and saying that Twitter "permanently suspended" your app and thus it's unlikely it will support Twitter (again) in the foreseeable future. Like:

> SNS client specialized to read in chronorogical order. You can access Twitter, Mastodon and Pleroma with API. ''Twitlatte'' supports multiple accounts.
>
> **Note:** Twitter has [permanently suspended this app](https://github.com/moko256/twitlatte/issues/54#issuecomment-574955039) – so it's unlikely *Twitlatte* will be able to support Twitter in the foreseeable future.

**Comment by moko256** [comment]
@IzzySoft Yes, please. Thanks for your comment.

**Comment by IzzySoft** [comment]
Gladly – and [done](https://gitlab.com/fdroid/fdroiddata/merge_requests/6210), so it will hopefully make it into the next index (which already is overdue).

Thanks again for your app. Used it quite a while to access my old birdsite account. Now, as indicated, I guess I'll stop using Twitter altogether. Should Twitter (against all expectations) lift the ban again, please update this issue (or ping me from a new one), so I can adjust the app description at F-Droid accordingly again.

**Comment by UTNMY** [comment]
I see.
I'm deeply sad at Twitter's rejection of Twitlatte.

**Comment by Mic92** [comment]
Please do not use these keys: https://gist.github.com/shobotch/5160017

**Comment by nuclearfog** [comment]
I faced the same problem. My app got suspended two times because someone has extracted my API keys from the APK file and used them for spaming. The best way to protect your API keys is to use a string obfuscation library (e.g. https://github.com/MichaelRocks/paranoid) with proguard enabled.
