### ISSUE TITLE
Twitter refuses like and subscription request

### ISSUE THREAD

**Issue by kirusyaga** [moko256/twitlatte#70]
Each time, when I try to like or subscribe via Twitlatte, app shows message "403: The request is understood, but it has been refused."
Sample message is in attachment.
![Screenshot_2020-01-03-16-44-28-557_com github moko256 twitlatte debug](https://user-images.githubusercontent.com/22245072/71726654-d6884800-2e48-11ea-80f1-79f93ec42226.jpg)

**Comment by DeWir3** [comment]
Seems to be #54 again. Twitter regularly restricts the devs API.

**Comment by Xray1870** [comment]
Can this be fixed again ?

**Comment by moko256** [comment]
This app was permanently suspended by Twitter.
I've requested to lift a read restriction, but it was no good...

* Please use ohter app.
* If you have a Twitter developer account, create a new app key and enter it in  login > ⁝ menu > "Use another consumer token", to keep using this app (Note: Do not publish your key. It is dangerous.)


Thank you for using twitlatte.
